"""Initial migration

Revision ID: 488b222bd1e8
Revises: 763980f45cc7
Create Date: 2022-09-03 12:57:27.576962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '488b222bd1e8'
down_revision = '763980f45cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'time_to_make')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('time_to_make', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
