"""Initial migration

Revision ID: 50b089e32222
Revises: fa8814c10548
Create Date: 2022-09-03 13:02:26.875572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b089e32222'
down_revision = 'fa8814c10548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('family_member', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'family_member')
    # ### end Alembic commands ###
