"""Initial migration

Revision ID: bc77105d103d
Revises: 50b089e32222
Create Date: 2022-09-03 13:04:22.164905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77105d103d'
down_revision = '50b089e32222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_diet_id_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'diet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('diet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('recipe_diet_id_fkey', 'recipe', 'diet', ['diet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
