"""Initial migration

Revision ID: f0b5d1e43885
Revises: 488b222bd1e8
Create Date: 2022-09-03 12:58:48.257157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b5d1e43885'
down_revision = '488b222bd1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('time_to_make', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'time_to_make')
    # ### end Alembic commands ###
