"""Initial migration

Revision ID: fa8814c10548
Revises: f0b5d1e43885
Create Date: 2022-09-03 13:01:39.664354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8814c10548'
down_revision = 'f0b5d1e43885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'family_member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('family_member', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
